"""
Convert the trained ONNX model for browser use and copy assets to client.

Input:  models/saved_model/asl_model.onnx + label_map.json
Output: client/public/models/asl_model.onnx + label_map.json + labelMap.ts
"""

import json
import shutil
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
PROJECT_DIR = SCRIPT_DIR.parent
MODEL_DIR = PROJECT_DIR / "models" / "saved_model"
OUTPUT_DIR = PROJECT_DIR.parent / "client" / "public" / "models"
LABEL_MAP_SRC = PROJECT_DIR / "data" / "processed" / "label_map.json"


def convert():
    onnx_src = MODEL_DIR / "asl_model.onnx"
    if not onnx_src.exists():
        print(f"ONNX model not found at {onnx_src}")
        print("Run train_model.py first.")
        sys.exit(1)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Copy ONNX model to client/public/models/
    shutil.copy(onnx_src, OUTPUT_DIR / "asl_model.onnx")
    print(f"Copied asl_model.onnx to {OUTPUT_DIR}")

    # Copy label map to client
    label_map_json = None
    if LABEL_MAP_SRC.exists():
        shutil.copy(LABEL_MAP_SRC, OUTPUT_DIR / "label_map.json")
        label_map_json = OUTPUT_DIR / "label_map.json"
        print("Copied label_map.json to client/public/models/")
    else:
        alt = MODEL_DIR / "label_map.json"
        if alt.exists():
            shutil.copy(alt, OUTPUT_DIR / "label_map.json")
            label_map_json = OUTPUT_DIR / "label_map.json"
            print("Copied label_map.json from model dir to client/public/models/")

    # List output files
    print("\nOutput files:")
    for f in sorted(OUTPUT_DIR.iterdir()):
        size_kb = f.stat().st_size / 1024
        print(f"  {f.name} ({size_kb:.1f} KB)")

    # Generate labelMap.ts from label_map.json
    if label_map_json and label_map_json.exists():
        with open(label_map_json) as f:
            label_map = json.load(f)

        # Sort by index
        max_idx = max(int(k) for k in label_map.keys())
        labels = [""] * (max_idx + 1)
        for idx_str, word in label_map.items():
            labels[int(idx_str)] = word

        ts_path = (PROJECT_DIR.parent / "client" / "src" / "features"
                   / "asl" / "models" / "labelMap.ts")
        lines = ["/**", " * Maps model output index to ASL word.",
                 " * Auto-generated by convert_to_tfjs.py — do not edit manually.",
                 " */", f"export const ASL_LABELS: string[] = ["]
        for i, word in enumerate(labels):
            comma = "," if i < len(labels) - 1 else ""
            lines.append(f"  '{word}'{comma}")
        lines.append("];")
        lines.append("")
        lines.append(f"export const NUM_CLASSES = {len(labels)};")
        lines.append(f"export const SEQ_LEN = 32;")
        lines.append(f"export const NUM_FEATURES = 126;")
        lines.append("")

        ts_path.write_text("\n".join(lines))
        print(f"\nGenerated {ts_path}")


if __name__ == "__main__":
    convert()
